fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 10.10.6.30:22122
#=================================================================================
# 自定义参数相关配置


#=================================================================================